apiVersion: v1
kind: Pod
//comentario Ricardo Castro
metadata:
  name: wordpress
  labels:
    app: web-wordpress
    microservice: wordpress
    version: v1
//comentario Jeimy Vargas
spec:
  containers:
    - name: wordpress
      image: wordpress:6.5.2-apache
      env:
        - name: WORDPRESS_DB_HOST
          value: svc-mysql
        - name: WORDPRESS_DB_USER
          value: wordpress_user
        - name: WORDPRESS_DB_PASSWORD
          value: asdf1234
        - name: WORDPRESS_DB_NAME
          value: wordpress_db
      ports:
        - containerPort: 80
